# Generated by Django 4.2.7 on 2023-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0003_remove_account_email_account_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_requster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Введиге имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Введиге пароль')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
