# Generated by Django 4.2.7 on 2023-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0005_delete_account_requster_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_code', models.CharField(max_length=6)),
            ],
        ),
    ]
